//! Conformance suite: runs every pair in `fixtures/cases/` through `diff()` at
//! both granularities and compares the serde JSON against the committed
//! reference output in `fixtures/expected/` (generated by
//! `scripts/gen-fixtures.mjs` from `reference/refdiff.mjs`).
//!
//! Policy (docs/scaffold-spec.md): cases where any minimal diff is unambiguous
//! assert exact output; ambiguous cases assert invariants instead. Since M4
//! the line level runs Myers O(ND), which may legitimately pick a
//! different-but-equally-minimal diff than the reference's LCS on ambiguous
//! inputs; such cases are demoted to `INVARIANT_CASES` below. The invariant
//! checks (tests/common/mod.rs) also run on all cases regardless.

mod common;

use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;

use common::{assemble, check_invariants, check_sparse_invariants};
use diffwtf_core::{diff, diff_sparse, DiffResult, Granularity, SparseDiff};
use serde_json::Value;

/// Cases demoted from the exact tier because Myers produces a
/// different-but-equally-minimal diff than the reference. Each entry needs a
/// comment showing the concrete disagreement (reference vs Myers, side by
/// side), and its added/removed/line_count must still equal the reference's
/// (equally minimal means identical counts). Currently EMPTY: as of M4,
/// Myers with prefer-delete tie-breaking and del-before-ins hunk
/// canonicalization reproduces the reference byte-for-byte on every fixture.
const INVARIANT_CASES: &[&str] = &[];

const GRANULARITIES: [(Granularity, &str); 2] =
    [(Granularity::Word, "word"), (Granularity::Char, "char")];

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures")
}

fn case_names() -> Vec<String> {
    let mut names: Vec<String> = fs::read_dir(fixtures_dir().join("cases"))
        .expect("fixtures/cases must exist")
        .map(|entry| {
            entry
                .expect("readable dir entry")
                .file_name()
                .into_string()
                .expect("UTF-8 file name")
        })
        .filter_map(|name| name.strip_suffix(".left.txt").map(str::to_string))
        .collect();
    names.sort();
    assert!(!names.is_empty(), "no cases found in fixtures/cases");
    names
}

fn read_case(name: &str) -> (String, String) {
    let cases = fixtures_dir().join("cases");
    let read = |side: &str| {
        let path = cases.join(format!("{name}.{side}.txt"));
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()))
    };
    (read("left"), read("right"))
}

/// Path to the first difference between two JSON values, with both values.
fn first_divergence(path: &str, actual: &Value, expected: &Value) -> Option<String> {
    match (actual, expected) {
        (Value::Object(a), Value::Object(e)) => {
            let keys: BTreeSet<&String> = a.keys().chain(e.keys()).collect();
            keys.into_iter().find_map(|k| {
                first_divergence(
                    &format!("{path}.{k}"),
                    a.get(k).unwrap_or(&Value::Null),
                    e.get(k).unwrap_or(&Value::Null),
                )
            })
        }
        (Value::Array(a), Value::Array(e)) => {
            if a.len() != e.len() {
                return Some(format!(
                    "{path}: array length {} != expected {}",
                    a.len(),
                    e.len()
                ));
            }
            a.iter()
                .zip(e)
                .enumerate()
                .find_map(|(i, (av, ev))| first_divergence(&format!("{path}[{i}]"), av, ev))
        }
        _ if actual != expected => Some(format!("{path}: {actual} != expected {expected}")),
        _ => None,
    }
}

/// Every case file pairs up, and expected/ holds exactly one word + one char
/// output per case — no strays, nothing missing.
#[test]
fn fixture_files_pair_up_exactly() {
    let names = case_names();
    let cases = fixtures_dir().join("cases");
    for name in &names {
        assert!(
            cases.join(format!("{name}.right.txt")).is_file(),
            "{name}.left.txt has no matching right file"
        );
    }
    let mut case_files: BTreeSet<String> = fs::read_dir(&cases)
        .expect("fixtures/cases must exist")
        .map(|e| {
            e.expect("dir entry")
                .file_name()
                .into_string()
                .expect("UTF-8")
        })
        .collect();
    for name in &names {
        case_files.remove(&format!("{name}.left.txt"));
        case_files.remove(&format!("{name}.right.txt"));
    }
    assert!(
        case_files.is_empty(),
        "stray files in fixtures/cases: {case_files:?}"
    );

    let expected: BTreeSet<String> = fs::read_dir(fixtures_dir().join("expected"))
        .expect("fixtures/expected must exist — run `node scripts/gen-fixtures.mjs`")
        .map(|e| {
            e.expect("dir entry")
                .file_name()
                .into_string()
                .expect("UTF-8")
        })
        .collect();
    let wanted: BTreeSet<String> = names
        .iter()
        .flat_map(|n| {
            ["word", "char"]
                .into_iter()
                .flat_map(move |g| [format!("{n}.{g}.json"), format!("{n}.{g}.ops.json")])
        })
        .collect();
    assert_eq!(
        expected, wanted,
        "fixtures/expected out of sync with fixtures/cases — run `node scripts/gen-fixtures.mjs`"
    );
}

#[test]
fn every_case_matches_the_reference_exactly() {
    let mut failures = Vec::new();
    for name in case_names() {
        let demoted = INVARIANT_CASES.contains(&name.as_str());
        let mut diverged = false;
        let (left, right) = read_case(&name);
        for (granularity, gran_name) in GRANULARITIES {
            // Both fixture tiers: the materialized DiffResult and the sparse
            // v2 boundary shape, each against its committed reference output.
            let tiers = [
                (
                    "json",
                    serde_json::to_value(diff(&left, &right, granularity))
                        .expect("DiffResult serializes"),
                ),
                (
                    "ops.json",
                    serde_json::to_value(diff_sparse(&left, &right, granularity))
                        .expect("SparseDiff serializes"),
                ),
            ];
            for (tier, actual) in tiers {
                let path = fixtures_dir()
                    .join("expected")
                    .join(format!("{name}.{gran_name}.{tier}"));
                let expected: Value = serde_json::from_str(
                    &fs::read_to_string(&path)
                        .unwrap_or_else(|e| panic!("reading {}: {e}", path.display())),
                )
                .unwrap_or_else(|e| panic!("parsing {}: {e}", path.display()));
                if actual == expected {
                    continue;
                }
                diverged = true;
                if demoted {
                    // Equally minimal diffs still agree on the counts.
                    for key in ["added", "removed", "line_count"] {
                        if actual.get(key) != expected.get(key) {
                            failures.push(format!(
                                "{name} ({gran_name}, {tier}): demoted case, but {key} {:?} != reference {:?}",
                                actual.get(key),
                                expected.get(key)
                            ));
                        }
                    }
                } else {
                    let at = first_divergence("$", &actual, &expected)
                        .unwrap_or_else(|| "unlocated".to_string());
                    failures.push(format!("{name} ({gran_name}, {tier}): {at}"));
                }
            }
        }
        if demoted && !diverged {
            failures.push(format!(
                "{name}: listed in INVARIANT_CASES but matches the reference exactly at both \
                 granularities; promote it back to the exact tier"
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "conformance policy violations:\n  {}",
        failures.join("\n  ")
    );
}

/// The contract invariants that must hold for ANY input, exact case or not:
/// row shape per kind, 1-based consecutive numbering, byte-exact input
/// reconstruction, honest counts, hunk ordering, and merged segments; plus
/// the sparse-shape invariants for `diff_sparse` (tests/common/mod.rs).
#[test]
fn every_case_satisfies_the_contract_invariants() {
    for name in case_names() {
        let (left, right) = read_case(&name);
        for (granularity, gran_name) in GRANULARITIES {
            let label = format!("{name} ({gran_name})");
            let result = diff(&left, &right, granularity);
            let sparse = diff_sparse(&left, &right, granularity);

            if left.trim().is_empty() && right.trim().is_empty() {
                assert_eq!(result, DiffResult::default(), "{label}: empty-state result");
                assert_eq!(sparse, SparseDiff::default(), "{label}: empty-state sparse");
                continue;
            }
            check_invariants(&label, &left, &right, &result);
            check_sparse_invariants(&label, &left, &right, &sparse);
        }
    }
}

/// The sparse shape is lossless: reassembling rows from the ops, the
/// highlights, and the two original inputs reproduces `diff()` exactly.
/// This is the equivalence the web renderer relies on when it derives the
/// Split and Unified views in JS instead of receiving them across the
/// boundary.
#[test]
fn every_case_reassembles_diff_from_diff_sparse() {
    for name in case_names() {
        let (left, right) = read_case(&name);
        for (granularity, gran_name) in GRANULARITIES {
            let sparse = diff_sparse(&left, &right, granularity);
            assert_eq!(
                assemble(&left, &right, &sparse),
                diff(&left, &right, granularity),
                "{name} ({gran_name}): reassembled views differ from diff()"
            );
        }
    }
}
