//! Conformance suite: runs every pair in `fixtures/cases/` through `diff()` at
//! both granularities and compares the serde JSON against the committed
//! reference output in `fixtures/expected/` (generated by
//! `scripts/gen-fixtures.mjs` from `reference/refdiff.mjs`).
//!
//! Policy (docs/scaffold-spec.md): cases where any minimal diff is unambiguous
//! assert exact output; ambiguous cases assert invariants instead. In this
//! milestone the engine is a 1:1 port of the reference's LCS algorithm, so
//! EVERY case is asserted exactly — a mismatch is a porting bug, not an
//! ambiguity. The invariant checks also run on all cases (they must hold
//! regardless, and they become the fallback tier when Myers lands).

use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;

use diffwtf_core::{diff, DiffResult, Granularity, RowKind, Segment, UnifiedKind};
use serde_json::Value;

const GRANULARITIES: [(Granularity, &str); 2] =
    [(Granularity::Word, "word"), (Granularity::Char, "char")];

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures")
}

fn case_names() -> Vec<String> {
    let mut names: Vec<String> = fs::read_dir(fixtures_dir().join("cases"))
        .expect("fixtures/cases must exist")
        .map(|entry| {
            entry
                .expect("readable dir entry")
                .file_name()
                .into_string()
                .expect("UTF-8 file name")
        })
        .filter_map(|name| name.strip_suffix(".left.txt").map(str::to_string))
        .collect();
    names.sort();
    assert!(!names.is_empty(), "no cases found in fixtures/cases");
    names
}

fn read_case(name: &str) -> (String, String) {
    let cases = fixtures_dir().join("cases");
    let read = |side: &str| {
        let path = cases.join(format!("{name}.{side}.txt"));
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()))
    };
    (read("left"), read("right"))
}

fn cell_text(segments: &[Segment]) -> String {
    segments.iter().map(|s| s.text.as_str()).collect()
}

/// Path to the first difference between two JSON values, with both values.
fn first_divergence(path: &str, actual: &Value, expected: &Value) -> Option<String> {
    match (actual, expected) {
        (Value::Object(a), Value::Object(e)) => {
            let keys: BTreeSet<&String> = a.keys().chain(e.keys()).collect();
            keys.into_iter().find_map(|k| {
                first_divergence(
                    &format!("{path}.{k}"),
                    a.get(k).unwrap_or(&Value::Null),
                    e.get(k).unwrap_or(&Value::Null),
                )
            })
        }
        (Value::Array(a), Value::Array(e)) => {
            if a.len() != e.len() {
                return Some(format!(
                    "{path}: array length {} != expected {}",
                    a.len(),
                    e.len()
                ));
            }
            a.iter()
                .zip(e)
                .enumerate()
                .find_map(|(i, (av, ev))| first_divergence(&format!("{path}[{i}]"), av, ev))
        }
        _ if actual != expected => Some(format!("{path}: {actual} != expected {expected}")),
        _ => None,
    }
}

/// Every case file pairs up, and expected/ holds exactly one word + one char
/// output per case — no strays, nothing missing.
#[test]
fn fixture_files_pair_up_exactly() {
    let names = case_names();
    let cases = fixtures_dir().join("cases");
    for name in &names {
        assert!(
            cases.join(format!("{name}.right.txt")).is_file(),
            "{name}.left.txt has no matching right file"
        );
    }
    let mut case_files: BTreeSet<String> = fs::read_dir(&cases)
        .expect("fixtures/cases must exist")
        .map(|e| {
            e.expect("dir entry")
                .file_name()
                .into_string()
                .expect("UTF-8")
        })
        .collect();
    for name in &names {
        case_files.remove(&format!("{name}.left.txt"));
        case_files.remove(&format!("{name}.right.txt"));
    }
    assert!(
        case_files.is_empty(),
        "stray files in fixtures/cases: {case_files:?}"
    );

    let expected: BTreeSet<String> = fs::read_dir(fixtures_dir().join("expected"))
        .expect("fixtures/expected must exist — run `node scripts/gen-fixtures.mjs`")
        .map(|e| {
            e.expect("dir entry")
                .file_name()
                .into_string()
                .expect("UTF-8")
        })
        .collect();
    let wanted: BTreeSet<String> = names
        .iter()
        .flat_map(|n| [format!("{n}.word.json"), format!("{n}.char.json")])
        .collect();
    assert_eq!(
        expected, wanted,
        "fixtures/expected out of sync with fixtures/cases — run `node scripts/gen-fixtures.mjs`"
    );
}

#[test]
fn every_case_matches_the_reference_exactly() {
    let mut failures = Vec::new();
    for name in case_names() {
        let (left, right) = read_case(&name);
        for (granularity, gran_name) in GRANULARITIES {
            let path = fixtures_dir()
                .join("expected")
                .join(format!("{name}.{gran_name}.json"));
            let expected: Value = serde_json::from_str(
                &fs::read_to_string(&path)
                    .unwrap_or_else(|e| panic!("reading {}: {e}", path.display())),
            )
            .unwrap_or_else(|e| panic!("parsing {}: {e}", path.display()));
            let actual = serde_json::to_value(diff(&left, &right, granularity))
                .expect("DiffResult serializes");
            if actual != expected {
                let at = first_divergence("$", &actual, &expected)
                    .unwrap_or_else(|| "unlocated".to_string());
                failures.push(format!("{name} ({gran_name}): {at}"));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "output diverges from the JS reference on:\n  {}",
        failures.join("\n  ")
    );
}

/// The contract invariants that must hold for ANY input, exact case or not:
/// row shape per kind, 1-based consecutive numbering, byte-exact input
/// reconstruction, honest counts, hunk ordering, and merged segments.
#[test]
fn every_case_satisfies_the_contract_invariants() {
    for name in case_names() {
        let (left, right) = read_case(&name);
        for (granularity, gran_name) in GRANULARITIES {
            let label = format!("{name} ({gran_name})");
            let result = diff(&left, &right, granularity);

            if left.trim().is_empty() && right.trim().is_empty() {
                assert_eq!(result, DiffResult::default(), "{label}: empty-state result");
                continue;
            }
            check_invariants(&label, &left, &right, &result);
        }
    }
}

fn check_invariants(label: &str, left: &str, right: &str, result: &DiffResult) {
    let left_lines = left.split('\n').count() as u32;
    let right_lines = right.split('\n').count() as u32;
    assert_eq!(
        result.line_count,
        left_lines.max(right_lines),
        "{label}: line_count"
    );

    // Split rows: shape per kind, and consecutive 1-based numbering per side.
    let (mut next_left, mut next_right) = (1u32, 1u32);
    let (mut modifies, mut deletes, mut inserts) = (0u32, 0u32, 0u32);
    for (i, row) in result.rows.iter().enumerate() {
        match row.kind {
            RowKind::Equal | RowKind::Modify => assert!(
                row.left.is_some() && row.right.is_some(),
                "{label}: row {i} ({:?}) must have both sides",
                row.kind
            ),
            RowKind::Delete => assert!(
                row.left.is_some() && row.right.is_none(),
                "{label}: row {i} (Delete) must be left-only"
            ),
            RowKind::Insert => assert!(
                row.left.is_none() && row.right.is_some(),
                "{label}: row {i} (Insert) must be right-only"
            ),
        }
        match row.kind {
            RowKind::Modify => modifies += 1,
            RowKind::Delete => deletes += 1,
            RowKind::Insert => inserts += 1,
            RowKind::Equal => {
                let (l, r) = (row.left.as_ref().unwrap(), row.right.as_ref().unwrap());
                assert_eq!(
                    l.segments, r.segments,
                    "{label}: row {i} Equal sides differ"
                );
                assert!(
                    l.segments.iter().all(|s| !s.highlighted),
                    "{label}: row {i} Equal row has highlights"
                );
            }
        }
        if let Some(cell) = &row.left {
            assert_eq!(cell.number, next_left, "{label}: row {i} left numbering");
            next_left += 1;
        }
        if let Some(cell) = &row.right {
            assert_eq!(cell.number, next_right, "{label}: row {i} right numbering");
            next_right += 1;
        }
        for cell in [&row.left, &row.right].into_iter().flatten() {
            for (s, pair) in cell.segments.windows(2).enumerate() {
                assert!(
                    pair[0].highlighted != pair[1].highlighted,
                    "{label}: row {i} segments {s},{} not merged",
                    s + 1
                );
            }
            assert!(
                cell.segments.iter().all(|s| !s.text.is_empty()),
                "{label}: row {i} has an empty-text segment"
            );
        }
    }
    assert_eq!(next_left - 1, left_lines, "{label}: left side line total");
    assert_eq!(
        next_right - 1,
        right_lines,
        "{label}: right side line total"
    );
    assert_eq!(result.removed, modifies + deletes, "{label}: removed count");
    assert_eq!(result.added, modifies + inserts, "{label}: added count");

    // Reconstructability: concatenating each side's segment text restores the
    // inputs byte-for-byte, through both views.
    let join = |texts: Vec<String>| texts.join("\n");
    let rows_left = join(
        result
            .rows
            .iter()
            .filter_map(|r| r.left.as_ref())
            .map(|c| cell_text(&c.segments))
            .collect(),
    );
    let rows_right = join(
        result
            .rows
            .iter()
            .filter_map(|r| r.right.as_ref())
            .map(|c| cell_text(&c.segments))
            .collect(),
    );
    assert_eq!(
        rows_left, left,
        "{label}: left does not reconstruct from rows"
    );
    assert_eq!(
        rows_right, right,
        "{label}: right does not reconstruct from rows"
    );

    // Unified rows: shape per kind, numbering, hunk ordering, reconstruction.
    let (mut next_old, mut next_new) = (1u32, 1u32);
    for (i, row) in result.unified.iter().enumerate() {
        match row.kind {
            UnifiedKind::Equal => assert!(
                row.old_number.is_some() && row.new_number.is_some(),
                "{label}: unified {i} Equal numbering shape"
            ),
            UnifiedKind::Delete => assert!(
                row.old_number.is_some() && row.new_number.is_none(),
                "{label}: unified {i} Delete numbering shape"
            ),
            UnifiedKind::Insert => assert!(
                row.old_number.is_none() && row.new_number.is_some(),
                "{label}: unified {i} Insert numbering shape"
            ),
        }
        if let Some(n) = row.old_number {
            assert_eq!(n, next_old, "{label}: unified {i} old numbering");
            next_old += 1;
        }
        if let Some(n) = row.new_number {
            assert_eq!(n, next_new, "{label}: unified {i} new numbering");
            next_new += 1;
        }
    }
    assert_eq!(next_old - 1, left_lines, "{label}: unified old line total");
    assert_eq!(next_new - 1, right_lines, "{label}: unified new line total");
    // Within a hunk all deletions precede all insertions, so Insert directly
    // followed by Delete can never occur anywhere in the stream.
    for (i, pair) in result.unified.windows(2).enumerate() {
        assert!(
            !(pair[0].kind == UnifiedKind::Insert && pair[1].kind == UnifiedKind::Delete),
            "{label}: unified {i}: Delete after Insert breaks hunk ordering"
        );
    }
    let unified_old = join(
        result
            .unified
            .iter()
            .filter(|u| u.old_number.is_some())
            .map(|u| cell_text(&u.segments))
            .collect(),
    );
    let unified_new = join(
        result
            .unified
            .iter()
            .filter(|u| u.new_number.is_some())
            .map(|u| cell_text(&u.segments))
            .collect(),
    );
    assert_eq!(
        unified_old, left,
        "{label}: left does not reconstruct from unified"
    );
    assert_eq!(
        unified_new, right,
        "{label}: right does not reconstruct from unified"
    );
}
